name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install yarn
      run: npm i --global yarn

    - name: Install npm packages
      run: yarn install

    - name: Build assets
      run: yarn build

    - name: Run test
      run: yarn test -- --watchAll=false
