# .github/workflows/preview.yml
name: preview
on:
  pull_request:
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: npm install --global vercel
      - run: vercel pull --yes --environment=preview --token=YOUR_VERCEL_TOKEN
      - run: vercel deploy --prebuilt  --token=YOUR_VERCEL_TOKEN
      - id: deploy
        run: echo "::set-output name=url::$(yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
